### ISSUE TITLE
Support for file uploads

### ISSUE THREAD

**Issue by jpmoodlerooms** [scriby/browser-harness#20]

**Comment by scriby** [comment]
It's possible to do file uploads using custom javascript in browsers that support blobs (IE > 9, and pretty much everything else).

You can pass the file to be uploaded as an array of bytes to the browser, then convert it to a Uint8Array, then to a Blob.

This code seems to work pretty well to do the conversion:

``` javascript
var arr = new Uint8Array(dataArray);
var blob = new window['Blob']([ arr.buffer ], { type: mimeType });
```
